/**
 * AI Error Normalization Utilities
 *
 * Detects provider/internal errors and normalizes them into AIError types.
 * NEVER exposes raw provider error details to users.
 * The friendly user-facing messages are generated by the executor.
 */

import {
  AIError,
  AITimeoutError,
  AIRateLimitError,
  AICreditsError,
  AINetworkError,
  AIProviderError,
  AIValidationError,
} from "../types/errors";

/**
 * Normalize any thrown error into a structured AIError.
 * Detects: 402 (credits), 429 (rate limit), 408/timeout, 5xx (server error),
 *          network errors, ECONNREFUSED, ECONNRESET, ETIMEDOUT, ENOTFOUND.
 *
 * @param error - The raw thrown error
 * @param providerName - Name of the provider (for logging only)
 */
export function normalizeAIError(error: unknown, providerName = "UnknownProvider"): AIError {
  // Already an AIError — pass through
  if (error instanceof AIError) {
    return error;
  }

  const errObj = error as any;
  const message: string = errObj?.message || String(error);
  const lowerMsg = message.toLowerCase();

  // Extract status code from various locations
  const status =
    errObj?.status ||
    errObj?.statusCode ||
    errObj?.response?.status ||
    errObj?.code; // e.g. ECONNREFUSED

  // ── Detect by status code ──────────────────────────
  if (status === 402 || (status && status === 402)) {
    return new AICreditsError("Insufficient credits or payment required", providerName);
  }

  if (status === 429 || (status && status === 429)) {
    return new AIRateLimitError("Rate limit exceeded", providerName);
  }

  if (status === 408) {
    return new AITimeoutError("AI request timed out", providerName);
  }

  if (status === 500 || status === 502 || status === 503 || status === 504) {
    return new AINetworkError(`Server error (${status})`, status, providerName);
  }

  // ── Detect by error message patterns ───────────────
  // Credit / billing / payment required
  if (
    lowerMsg.includes("402") ||
    lowerMsg.includes("credit") ||
    lowerMsg.includes("billing") ||
    lowerMsg.includes("payment required") ||
    lowerMsg.includes("insufficient") ||
    lowerMsg.includes("exceeded your current quota") ||
    lowerMsg.includes("out of credits")
  ) {
    return new AICreditsError(message, providerName);
  }

  // Rate limiting
  if (
    lowerMsg.includes("429") ||
    lowerMsg.includes("rate limit") ||
    lowerMsg.includes("rate_limit") ||
    lowerMsg.includes("too many requests") ||
    lowerMsg.includes("throttled")
  ) {
    return new AIRateLimitError(message, providerName);
  }

  // Timeouts
  if (
    lowerMsg.includes("408") ||
    lowerMsg.includes("timeout") ||
    lowerMsg.includes("timed out") ||
    lowerMsg.includes("timed_out") ||
    lowerMsg.includes("deadline exceeded") ||
    lowerMsg.includes("etimedout") ||
    lowerMsg.includes("time_out")
  ) {
    return new AITimeoutError(message, providerName);
  }

  // Network errors
  if (
    lowerMsg.includes("network") ||
    lowerMsg.includes("econnrefused") ||
    lowerMsg.includes("econnreset") ||
    lowerMsg.includes("enotfound") ||
    lowerMsg.includes("eai_again") ||
    lowerMsg.includes("socket") ||
    lowerMsg.includes("fetch failed") ||
    lowerMsg.includes("request failed") ||
    lowerMsg.includes("connect") ||
    lowerMsg.includes("dns") ||
    (status && (status === "ECONNREFUSED" || status === "ECONNRESET" || status === "ENOTFOUND" || status === "ETIMEDOUT"))
  ) {
    return new AINetworkError(message, 503, providerName);
  }

  // Server errors (5xx)
  if (
    lowerMsg.includes("500") ||
    lowerMsg.includes("502") ||
    lowerMsg.includes("503") ||
    lowerMsg.includes("504") ||
    lowerMsg.includes("internal server error") ||
    lowerMsg.includes("service unavailable") ||
    lowerMsg.includes("bad gateway")
  ) {
    return new AINetworkError(message, 503, providerName);
  }

  // Validation errors (4xx except those handled above)
  if (status === 400 || status === 422 || status === 401 || status === 403) {
    return new AIValidationError(message);
  }

  // Default: generic provider error, retryable
  return new AIProviderError(message, status || 500, providerName, true);
}
